/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRedPillRouteImport } from './routes/_authenticated/red-pill'
import { Route as AuthenticatedChooseRouteImport } from './routes/_authenticated/choose'
import { Route as AuthenticatedBluePillRouteImport } from './routes/_authenticated/blue-pill'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/account/route'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAccountCoursesRouteImport } from './routes/_authenticated/account/courses'
import { Route as AuthenticatedAccountBillingRouteImport } from './routes/_authenticated/account/billing'
import { Route as AuthenticatedAccountApplicationRouteImport } from './routes/_authenticated/account/application'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as AuthenticatedAccountCoursesSlugRouteImport } from './routes/_authenticated/account/courses.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedPillRoute = AuthenticatedRedPillRouteImport.update({
  id: '/red-pill',
  path: '/red-pill',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChooseRoute = AuthenticatedChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBluePillRoute = AuthenticatedBluePillRouteImport.update({
  id: '/blue-pill',
  path: '/blue-pill',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountCoursesRoute =
  AuthenticatedAccountCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountBillingRoute =
  AuthenticatedAccountBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountApplicationRoute =
  AuthenticatedAccountApplicationRouteImport.update({
    id: '/application',
    path: '/application',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountCoursesSlugRoute =
  AuthenticatedAccountCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAccountCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/blue-pill': typeof AuthenticatedBluePillRoute
  '/choose': typeof AuthenticatedChooseRoute
  '/red-pill': typeof AuthenticatedRedPillRoute
  '/account/application': typeof AuthenticatedAccountApplicationRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/account/courses': typeof AuthenticatedAccountCoursesRouteWithChildren
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/account/courses/$slug': typeof AuthenticatedAccountCoursesSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blue-pill': typeof AuthenticatedBluePillRoute
  '/choose': typeof AuthenticatedChooseRoute
  '/red-pill': typeof AuthenticatedRedPillRoute
  '/account/application': typeof AuthenticatedAccountApplicationRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/account/courses': typeof AuthenticatedAccountCoursesRouteWithChildren
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/account/courses/$slug': typeof AuthenticatedAccountCoursesSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/_authenticated/blue-pill': typeof AuthenticatedBluePillRoute
  '/_authenticated/choose': typeof AuthenticatedChooseRoute
  '/_authenticated/red-pill': typeof AuthenticatedRedPillRoute
  '/_authenticated/account/application': typeof AuthenticatedAccountApplicationRoute
  '/_authenticated/account/billing': typeof AuthenticatedAccountBillingRoute
  '/_authenticated/account/courses': typeof AuthenticatedAccountCoursesRouteWithChildren
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/account/courses/$slug': typeof AuthenticatedAccountCoursesSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/blue-pill'
    | '/choose'
    | '/red-pill'
    | '/account/application'
    | '/account/billing'
    | '/account/courses'
    | '/account/profile'
    | '/account/'
    | '/account/courses/$slug'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blue-pill'
    | '/choose'
    | '/red-pill'
    | '/account/application'
    | '/account/billing'
    | '/account/courses'
    | '/account/profile'
    | '/account'
    | '/account/courses/$slug'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/blue-pill'
    | '/_authenticated/choose'
    | '/_authenticated/red-pill'
    | '/_authenticated/account/application'
    | '/_authenticated/account/billing'
    | '/_authenticated/account/courses'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/'
    | '/_authenticated/account/courses/$slug'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/red-pill': {
      id: '/_authenticated/red-pill'
      path: '/red-pill'
      fullPath: '/red-pill'
      preLoaderRoute: typeof AuthenticatedRedPillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose': {
      id: '/_authenticated/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof AuthenticatedChooseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blue-pill': {
      id: '/_authenticated/blue-pill'
      path: '/blue-pill'
      fullPath: '/blue-pill'
      preLoaderRoute: typeof AuthenticatedBluePillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/courses': {
      id: '/_authenticated/account/courses'
      path: '/courses'
      fullPath: '/account/courses'
      preLoaderRoute: typeof AuthenticatedAccountCoursesRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/billing': {
      id: '/_authenticated/account/billing'
      path: '/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AuthenticatedAccountBillingRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/application': {
      id: '/_authenticated/account/application'
      path: '/application'
      fullPath: '/account/application'
      preLoaderRoute: typeof AuthenticatedAccountApplicationRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/courses/$slug': {
      id: '/_authenticated/account/courses/$slug'
      path: '/$slug'
      fullPath: '/account/courses/$slug'
      preLoaderRoute: typeof AuthenticatedAccountCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedAccountCoursesRoute
    }
  }
}

interface AuthenticatedAccountCoursesRouteChildren {
  AuthenticatedAccountCoursesSlugRoute: typeof AuthenticatedAccountCoursesSlugRoute
}

const AuthenticatedAccountCoursesRouteChildren: AuthenticatedAccountCoursesRouteChildren =
  {
    AuthenticatedAccountCoursesSlugRoute: AuthenticatedAccountCoursesSlugRoute,
  }

const AuthenticatedAccountCoursesRouteWithChildren =
  AuthenticatedAccountCoursesRoute._addFileChildren(
    AuthenticatedAccountCoursesRouteChildren,
  )

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountApplicationRoute: typeof AuthenticatedAccountApplicationRoute
  AuthenticatedAccountBillingRoute: typeof AuthenticatedAccountBillingRoute
  AuthenticatedAccountCoursesRoute: typeof AuthenticatedAccountCoursesRouteWithChildren
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountApplicationRoute: AuthenticatedAccountApplicationRoute,
    AuthenticatedAccountBillingRoute: AuthenticatedAccountBillingRoute,
    AuthenticatedAccountCoursesRoute:
      AuthenticatedAccountCoursesRouteWithChildren,
    AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
    AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedBluePillRoute: typeof AuthenticatedBluePillRoute
  AuthenticatedChooseRoute: typeof AuthenticatedChooseRoute
  AuthenticatedRedPillRoute: typeof AuthenticatedRedPillRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedBluePillRoute: AuthenticatedBluePillRoute,
  AuthenticatedChooseRoute: AuthenticatedChooseRoute,
  AuthenticatedRedPillRoute: AuthenticatedRedPillRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
